flowchart TD

    Client -->|DNS Requst| v2ray

    subgraph v2ray
        inbounds[dokodemo-door] -->|tag: dns_in| Router -->|forward| outbounds -->|protocol: dns| DNS[DNS CacheDisabled]
    end

    v2ray -->|geosite:cn| Unbound[OPNsense DNS]
    v2ray -->|default route| FAKEDNS[Meta DNS]

    