flowchart TD

    client --> OPNsense

    subgraph v2ray
        inbounds[dokodemo-door] -->|tag: dns_in| Router -->|forward| outbounds -->|protocol: dns| DNS
    end

    v2ray -->|geosite:cn| ISPDNS
    v2ray -->|others| FAKEDNS

    OPNsense -->|Default| PPPOE
    OPNsense -->|FAKEIP| META
    OPNsense -->|DNS| v2ray