flowchart TD

    Client -->|DNS Requst| v2ray

    subgraph v2ray
        inbounds[dokodemo-door] -->|tag: dns_in| Router -->|forward| outbounds -->|protocol: dns| DNS[DNS CacheDisabled]
    end

    v2ray -->|geosite:cn| LOCALDNS
    v2ray -->|default| FAKEDNS

    Client -->|TCP/UDP| Gateway

    subgraph Gateway[OPNsense]
        LAN[Incoming Connections] --> |src: !TUN dst: FakeIP Range| TUN[TUN: Rule base proxy] -->|dst: Proxies| WAN_PPOE
        LAN --> |others|WAN_PPOE
    end

    